# Generated by Django 5.0.6 on 2024-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_class_newsnevents_schoolinfo_staff_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_school', models.CharField(max_length=255)),
                ('affiliation_no', models.CharField(blank=True, max_length=100, null=True)),
                ('school_code', models.CharField(blank=True, max_length=100, null=True)),
                ('complete_address', models.TextField()),
                ('principal_name_and_qualification', models.CharField(max_length=255)),
                ('school_email_id', models.EmailField(max_length=254)),
                ('contact_details', models.CharField(max_length=100)),
                ('copies_of_affiliation_letter', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('copies_of_societies_registration_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('copy_of_noc_issued_by_state_govt', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('copies_of_recognition_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('copy_of_valid_building_safety_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('copy_of_valid_fire_safety_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('copy_of_deo_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('copies_of_valid_water_health_sanitation_certificates', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('fee_structure_of_the_school', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('annual_academic_calendar', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('list_of_school_management_committee', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('list_of_parents_teachers_association_members', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('last_three_years_board_exam_results', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('principal', models.CharField(max_length=255)),
                ('total_no_of_teachers', models.IntegerField()),
                ('pgt_teachers', models.IntegerField()),
                ('tgt_teachers', models.IntegerField()),
                ('prt_teachers', models.IntegerField()),
                ('teachers_section_ratio', models.FloatField()),
                ('details_of_special_educator', models.TextField()),
                ('details_of_counsellor_and_wellness_teacher', models.TextField()),
                ('total_campus_area', models.FloatField()),
                ('no_and_size_of_classrooms', models.TextField()),
                ('no_and_size_of_laboratories', models.TextField()),
                ('internet_facility', models.BooleanField(default=False)),
                ('no_of_girls_toilets', models.IntegerField()),
                ('no_of_boys_toilets', models.IntegerField()),
                ('youtube_link_of_inspection_video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
