# Generated by Django 5.0.6 on 2024-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('our_mission', models.TextField()),
                ('our_vision', models.TextField()),
            ],
        ),
    ]
