# Generated by Django 5.0.6 on 2024-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_aboutschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_principal', models.CharField(max_length=100)),
                ('our_finance_manager', models.CharField(max_length=100)),
                ('our_local_manager', models.CharField(max_length=100)),
            ],
        ),
    ]
