# Generated by Django 5.0.6 on 2024-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='finance_manager_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='management',
            name='local_manager_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='management',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='management',
            name='our_finance_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='our_local_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='our_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
