# Generated by Django 5.0.6 on 2024-05-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_management_finance_manager_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
