# Generated by Django 5.0.6 on 2024-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='total_classrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='total_non_teaching_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='total_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='total_teaching_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='total_transportation_vehicles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
