# Generated by Django 5.0.6 on 2024-06-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_schoolinfo_total_classrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
