# Generated by Django 5.0.6 on 2024-06-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_class_class_teacher_delete_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='total_non_teaching_staff',
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='total_teaching_staff',
        ),
    ]
