# Generated by Django 5.0.6 on 2024-06-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_schoolinfo_total_non_teaching_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
