# Generated by Django 5.0.6 on 2024-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='principal_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
