# Generated by Django 5.0.6 on 2024-07-13 08:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_management_principal_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='principal_message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
